---
title: "Model Selection"
author: "Cindy J. Pang, Jonathan Hori"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r}
rm(list=ls())
```

```{r, results='hide', warnings = FALSE}
source("../src/models.R")
```

# Cox-PH Models.  

```{r}
CoxPH.aic
CoxPH.bic
```

# Exponential AFT Models. 

```{r}
expAFT.aic
expAFT.bic
```

# Weibull AFT Models.  

```{r}
weibullAFT.aic
weibullAFT.bic
```

# Log-Logistic AFT Models. 
```{r}
loglogisticAFT.aic
loglogisticAFT.bic
```

# Log-Normal AFT Models. 
```{r}
lognormalAFT.aic
lognormalAFT.bic
```



# Aggregate effect sizes

```{r}
library(kableExtra)
library(tidyverse)
```


```{r}
# Cox
cox_summary <- summary(CoxPH.aic)$coefficients[, c(2, 3, 5)] |> 
  as.data.frame() |> 
  rownames_to_column()
names(cox_summary) <- c("predictor", "effect_size", "se", "p")

# Exp AFT
exp_summary <- summary(expAFT.aic)#$coefficients
exp_summary <- exp_summary$table[, c(1, 2, 4)] |> 
  as.data.frame() |> 
  rownames_to_column() #|> 
names(exp_summary) <- c("predictor", "effect_size", "se", "p")

# Weibull AFT
weib_summary <- summary(weibullAFT.aic)#$coefficients
weib_summary <- weib_summary$table[, c(1, 2, 4)] |> 
  as.data.frame() |> 
  rownames_to_column() #|> 
names(weib_summary) <- c("predictor", "effect_size", "se", "p")

# Loglogistic AFT
loglogist_summary <- summary(loglogisticAFT.aic)#$coefficients
loglogist_summary <- loglogist_summary$table[, c(1, 2, 4)] |> 
  as.data.frame() |> 
  rownames_to_column() #|> 
names(loglogist_summary) <- c("predictor", "effect_size", "se", "p")

# Lognormal AFT
ln_summary <- summary(lognormalAFT.aic)#$coefficients
ln_summary <- ln_summary$table[, c(1, 2, 4)] |> 
  as.data.frame() |> 
  rownames_to_column() #|> 
names(ln_summary) <- c("predictor", "effect_size", "se", "p")

# Join
list(
  cox_summary |> pivot_longer(-predictor, values_to = "Cox"),
  exp_summary |> pivot_longer(-predictor, values_to = "Exponential"),
  weib_summary |> pivot_longer(-predictor, values_to = "Weibull"),
  loglogist_summary |> pivot_longer(-predictor, values_to = "Log-logistic"),
  ln_summary |> pivot_longer(-predictor, values_to = "Log-normal")
) |> 
  reduce(full_join, by = c("predictor", "name")) |> 
  mutate(across(is.numeric, ~round(.x, 3))) |> 
  dplyr::select(-predictor) |>
  # filter(name == "effect_size") |>
  kbl() |> 
  kable_classic(html_font = "Cambria") |> 
  pack_rows(
    index = c(
      "Race: Asian" = 3,
      "Race: Black" = 3,
      "Race: Hispanic" = 3,
      "Race: Other" = 3,
      "FIGO: II" = 3,
      "FIGO: III" = 3,
      "FIGO: IV" = 3,
      "Age at diagnosis" = 3,
      "Intercept" = 3,
      "Biopsy size" = 3,
      "Log scale" = 3
    )
  ) |> 
  save_kable(file = "effect_sizes.html")
  



  # pivot_longer(-c("predictor", "name"), names_to = "model", values_to = "est") #|> 
  # pivot_wider(
  #   id_cols = predictor,
  #   names_from = model
  #   id_cols = model,
  #   names_from = predictor,
  #             values_from = est)
```

