---
title: "Variable Selection and Model Diagnostics"
author: "Cindy J. Pang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r, warnings = FALSE}
rm(list=ls())
library(dplyr)
library(survival)
library(survMisc)
```

```{r}
source("../src/models.R")
source("../src/CoxSnellResidualPlot.R")
```

```{r}
par(mfrow = c(1,3))
plotCoxSnellCPH(CoxPH.aic, data.raceCleaned$delta, "AIC")
plotCoxSnellCPH(CoxPH.bic, data.raceCleaned$delta, "BIC")
plotCoxSnellCPH(fullCoxMod, data.raceCleaned$delta, "Full Variable")

par(mfrow = c(1,3))
plotCSExpAFT(expAFT.aic, data.raceCleaned, "AIC")
plotCSExpAFT(expAFT.bic, data.raceCleaned, "BIC")
plotCSExpAFT(full.expAFT, data.raceCleaned, "Full")

par(mfrow = c(1,3))
plotCSWeibullAFT(weibullAFT.aic, data.raceCleaned, "AIC")
plotCSWeibullAFT(weibullAFT.bic, data.raceCleaned, "BIC")
plotCSWeibullAFT(full.weibullAFT, data.raceCleaned, "Full")

par(mfrow = c(1,3))
plotCSLogLogisticAFT(loglogisticAFT.aic, data.raceCleaned, "AIC")
plotCSLogLogisticAFT(loglogisticAFT.bic, data.raceCleaned, "BIC")
plotCSLogLogisticAFT(full.loglogisticAFT, data.raceCleaned, "Full")

par(mfrow = c(1,3))
plotCSLogNormalAFT(lognormalAFT.aic, data.raceCleaned, "AIC")
plotCSLogNormalAFT(lognormalAFT.bic, data.raceCleaned, "BIC")
plotCSLogNormalAFT(full.lognormalAFT, data.raceCleaned, "Full")
```




